### ISSUE TITLE
Use `JsonValue` as `JSON.parse` Return Type?

### ISSUE THREAD

**Issue by joealden** [total-typescript/ts-reset#10]
Perhaps this would go further that what is wanted from this library, but I think it'd be nice if `JSON.parse` could return a type similar to (or the same as) `JsonValue` from `type-fest` (see https://github.com/sindresorhus/type-fest#json).

I've never used the optional `reviver` function in `JSON.parse`, but it looks like it can modify the return type beyond `JsonValue`, so perhaps it'd make sense to have a return type of  `JsonValue` if no `reviver` is passed, then `unknown` if a `reviver` is passed?

**Comment by mattpocock** [comment]
I think `unknown` here is safer, but I'll leave this issue open!

**Comment by j** [comment]
```typescript
interface JSON {
  parse<T = unknown>(
    text: string,
    reviver?: (this: any, key: string, value: any) => any,
  ): T;
}
```

**Comment by joealden** [comment]
@j if the aim is type safety, that isn't safe

**Comment by mattpocock** [comment]
@j Hiding this as not relevant to the issue. Please also take a look at the readme, where I mention in detail the reason why we won't be implementing this.

**Comment by j** [comment]
@mattpocock 

true; understood.  I live in a world where I consume self-owned APIs and messages that are type-safe at the point of having to parse it, so my brain went there.

with that said, leaving as `unknown` and forcing narrowing or casting is better.

**Comment by m10rten** [comment]
Same applies to `JSON.stringify`:`reviver` btw ^.^

**Comment by wmertens** [comment]
I'd like to see JsonValue when no reviver too. I can't see how it's less safe?

**Comment by mattpocock** [comment]
OK - I think I prefer unknown here instead of `JSONValue`. The reason is that narrowing based on `unknown` is actually more productive. With `JSONValue` you actually lose a lot of value in the return type, preventing you from narrowing properly:

https://www.typescriptlang.org/play?#code/PQKhCgFkEMBcGMAWBTAzgAmugUgZQPIBy6A9gEYBWy8sAdOACqICWGsAngA7LrzQB26MjwCuqZADMRAG3SwS6ZPwkkATvB6oSAWx7N+nEbDkLhOAoQC08HZzjMy0nmswYsqEd1WWO3E0J5kAA9YJQATZDD0CVUdWnQAERJ+AHJjMR5YFjc3dDDmVWpjQtgRVUFfHmg2FHQM1XQAdxIZKMRoADdMhTCWx2RrauNmWAAudAADCi1+fEoi1zr+AGt+EkbBavQAYTF5bQAlNE5k8Qn4gEl+VFDoMIAadHYW3hbpKODQ-ijnsp29nRHVAna6ZLg8GI6dAjfxKDyFJ4tBqVUj8aTsOriDB4IjWWz2fpycGocYTfShVQSaAaf43QHHU6BELhbEzOZUGjoADe6EAZAToAC+53AAAE+KEAOZqDE4wjgEDAcDBE6qYwo7Bs+acgC83PQAG0ANLIDH6dA3VT6CUAXXGGuSADVoNIRDwBegAGR6o0m6GCC1W60AfjtMydLp4AB8lhEJPpIoKANzgcCgCAwBAoXKyzCqVTQdj0MVwZBS1QyizyxXKtRq8E4GYAQTzBfQuvt-HDrv11vQ0cKd2S6Ibjud3etydTYCgcCQaEw-AxHWdzCiOc4lu0I2YXXQy4jRfFpel5iIVaVQRVdb8HYACpvt7vdQH+BK++h+CJtMIGtGyCQSCcAR30-aRpEnNMZ0zecBCXFc1wsPcx2QItxB4CYO2YCR2AmaEJEREQP2QBN5DkfNrhUVRtEwIk-FI5JMnaYYclQZgJX4aBCVIjCw2Q4Vi0lE9ZXPGtVVongOy7Hh2xme9mC3WAdyjEdZi1Yxow7Zt83YScIngaRoARCVpHIZ1uRTclkEpakJMQrlwHQdBIMc9AQB2ZIulVbNOmgXB4EtThjHZBZCBIWB7GSdAAApZQASnNWBLVfP1SOA8gOToBzHLckU7HzajQhCdBGyQ6RV1PYgXwlegXJyvLoGowoOiUhoSqkfgaGYSKsjgMiBFQSjtBqHhCg8aRYFQeImFYaIRA6xTIpmvgwITSjFGpRB0F0b8rNIfCsmcNSauy9ALnwrBtp-V5+HC-QMH4NBQiidKilQR4DqIm4Exemg3ARRL+sGhNhEoxieDypRjB+5jjtcxVHLy8QoqyxzCrGBKkole4UfQJqWpDaKslYcZYMeZYTXGKrHn3V0ScXeLtQAPgXdhscc2LQ1HCNkwFcBefAGxrmKNAZGMdsLFoRHkCilIuQFFJYos-CosqEh8NG0W221XUUmhlJPS9DXxoN9AUkaJjkE8-WzSN2B4vsxzgGAU7zUQN4ojMCVkFgRTkugIwSBsbROCcUJohcM2LatrKnYXKJgKs2IGjWlJoEaMJlgoAR08z1Istt2g04zrP+Bzih+D5oA

**Comment by aaditmshah** [comment]
I created a PR, #123, for a type-safe and sound version of `JSON.parse` if anybody is interested. I also wrote a good description of the problem statement and the solution that I implemented.

**Comment by aaditmshah** [comment]
@mattpocock Consider the following [playground example](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&noPropertyAccessFromIndexSignature=false#code/KYDwDg9gTgLgBDAnmYcBSBnCA7AClASwFsCYCA3VAXjgxkOwHM4AfObAVyICNgpW43CBAA2wAIbYBnESIDcAKAWhIsBMlSYcANXEiO1dFjyESZSgK3YA8twBWwAMbw2V3fuABtALqLl4aHgkFCMcWwdnOBoAbzhPAGtgRAAuWnoCJm9Utz0DOABfPxVA9RCrAEERRmBuKHEAHnKAPijQk2JSClQ2ACUnaAATeroGRgAaOGaBcp8igLVgzWMACVEBvnqAaThQGGBsAYw00Ympmj7HQa2Jiqqausampr91xxFxKFRGEQhuPThogo4HAMnsoAAzcSOTQAZWsADkAUDgXAwB8MMAABR7EAwVIjDKMACU2WM7gMfhRqPRwEarQ42Hi2AgAHdsE1MciqTi8cdCWMuSjPuQulBUlsdrj9oc+UwOYLuQALAgYUk4VYidZQa6TJoCqlUxIpOCbfUG4HkXLANXYSrVWoNZpmqlEqItcrOuAkyaKYH5BT+hSXbB0OCfDAcETwGhoOHwgB0aKgGMxAHJovlU0SlARwXBsRoIHnw5Ho1QaKnfhEYKm4AAyOth4ARqP1xuplmK8R7ShQWsZJstmCuwHAgD0Y7gAElaIqIJGBoIvsAYGQmHBxBwYBBLkQwGI9nBwdA4B2uz2+KnkRONwdbzsoFAT8f+KnxCyBvE7JIP1-sFfgUWOAAFFwCcGB6gAFUlPYDiOegDBaGhIN9UpUGAgBHDg9HqAANCYAE0kPzKCOVdKgWmg3ZpSOXC4AAfjgABGOBUgAJldai4LgUjMXIyiYJouACIY5jWLgNjBUYhDgEFVJIREDFKTgYNQ07btgF7VoSyjeN1IvKBkVU+B30-b9sF-OwpBoHSYHjUyvx-MzsCUQCNAQZsYCOGhPEFUCUGcepMOwkR6kWIs4H0zS+BuMkrSeT1-PAoKsJw8K8wc8zLOwWKdCtAQGXWcEMmAAYnmRXwAyAA). With `noUncheckedIndexedAccess` you can see that the type of `result.whatever` is just `JsonValue`, but the type of `result.awdkjanwdkjn` is `JsonValue | undefined`. You may not get autocomplete for `whatever` and an error for `awdkjanwdkjn`, but this is the next best thing.
