### ISSUE TITLE
Object.keys(obj) returns a string[]

### ISSUE THREAD

**Issue by Relaxe111** [total-typescript/ts-reset#131]
Hi, Obj.keys(obj) retruns always a string[]. With small d.ts addon we can make it more save:
original:
<img width="497" alt="image" src="https://user-images.githubusercontent.com/40892030/229343480-f2abb063-2623-4bd7-bab5-3a34e8c617bc.png">
with d.ts def:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/40892030/229343536-c1b7cba5-64d4-4b75-b909-6ad89c7bd00d.png">
here is the def:

```
//object.d.ts
interface ObjectConstructor {
  keys<T extends object>(obj: T): (keyof T)[];
}
```
Do you think it is wise to add this as well to ts-reset maybe? Eventually i can do a PR, if that's will be accepted :)

**Comment by mattpocock** [comment]
Check the readme!

**Comment by hakimio** [comment]
@mattpocock what are you supposed to find in the readme?
Also, your docs page is broken: https://www.totaltypescript.com/ts-reset#get-started

**Comment by hakimio** [comment]
I guess this removed section: https://github.com/total-typescript/ts-reset/blob/5c20842406b9dd3fe9e533357ee6a2aa092b4e08/readme.md#rules-we-wont-add
The library has very little value without the rules you are not willing to add...

**Comment by Evertt** [comment]
@mattpocock on your website I saw the reasoning for letting `Object.keys` keep returning `Array<string>` is:

> One of the effects of this is that TypeScript can't always guarantee that your object types don't contain excess properties

Okay, so that means that whatever `Object.keys` returns is *either* exactly `Array<keyof T>` or otherwise it must be a **superset** of `Array<keyof T>`, right? If that is correct, then why not change the return-type into `Array<keyof T | (string & {})>`. That way we get the best of both worlds. We get auto-complete for the keys we know are in there, and we don't get incorrect type-errors for any other random string.
