### ISSUE TITLE
The `.filter(Boolean)` doesn't seem to be working as expected

### ISSUE THREAD

**Issue by u3u** [total-typescript/ts-reset#146]
```ts
// Actual: `(number | true)[]`
// Expectation: `number[]`
const numbers = [1, 0, false, null, undefined].filter(Boolean)
```

[TS Playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEA7KBbEBnADlMCAqAygEoYgAu8A3gFDzxkCemCAcgPaIBiUE6DAPHgB88ALzw88EAA8yIRMHTwAZj3QIAPvAAM8LQCJ9epAFcIEYyYUhlAS0Qhgx7Ylp14AfiQgAbiBhudABcEgDc1G6MzPAA6ragiAAytnIwPIIi4pIycgpK6GQw9gDmgZ7wBUWIpe7wIdmy8oqmKABG-mVeiCZtHbX1Uo158K1sbBAgUK61XqPjk9PuAzlNSq22xfZknSMbW2XLQ818beM7J6MQB2HUAL4R1Fv+qrjwAIIwaQLCVG52EKkABSYODAWxgKByEIAITGEymAGEOJUTGAyGwYAAaegAC1s6A+xQ8ISmDAAlPViKQyAA6dhcNTfIQAbQAuuF7o9EKkXggSFBgBwIAwPl8Mr86P8gSDHODISAYXCFkjECi0RjsWQ8QSYESSYhyZSSOpafTuLwmWyOREwMiKN1ejAlOJmQBGbHabGqXggbHdczYqygOwOYCsmlS-yA2HzKZk6hAA)

**Comment by JakeTrevor** [comment]
`True` won't get filtered out by this (resulting in an array `[1, 0, true]`) so the type signature is actually correct - not quite sure what you mean @u3u.

There is some weirdness with `.filter` I have encountered, but it's to do with 2D-arrays; here's an example:

```ts
function makeRows({
  row1,
  row2,
  row3,
  row4,
  row5,
}: {
  row1?: number[];
  row2?: number[];
  row3?: number[];
  row4?: number[];
  row5?: number[];
}) {
  let rows = [row1, row2, row3, row4, row5];
  rows = rows.filter(Boolean);
  //^? let rows: (number[] | undefined)[]
 // But I expect number[][]
}
```
Am I missing something?

**Comment by u3u** [comment]
@JakeTrevor Sorry, the example I gave may have some problems. 
In fact, it is the following code that still infers as `(number | true)[]`, but the actual result should be `number[]`.

```ts
const numbers = [1, 0, false, null, undefined].filter(Boolean)
```

**Comment by JakeTrevor** [comment]
Weird as it is, the behaviour actually is correct; Take a clook at this screen cap:
![image](https://github.com/total-typescript/ts-reset/assets/50667410/ad6ae9f0-1f6a-4374-b772-05109fbdb3ca)
As you can see, the type of the array you are filtering includes a bunch of falsey values, numbers and booleans. All the falsey values will get filtered out, resulting in numbers and booleans. But non-falsey booleans are of course all true - so we get a final type of `number | true`.

In this context, typescript knows nothing about the contents of the array - all it knows is that it contains some number of booleans. So all it can assert is that the resulting filtered array may contains numbers or `true`.

If you tell typescript the array contains only `false` instances, not booleans, it does get it right. see below:
![image](https://github.com/total-typescript/ts-reset/assets/50667410/1e028810-3976-4a10-b73b-4d5eace5ce0b)

However for very good reasons, typescript does not assume this, instead widening the type to `boolean`, instead of just `false`. You can also get it to work by casting the array as const:
![image](https://github.com/total-typescript/ts-reset/assets/50667410/4e78efc1-0350-4179-8e25-03442093f8c9)

In this case you are telling typescript that the contents of the array will only ever be what you describe in this literal, and so it can make even further inferences. 

However this should this should certainly not happen by default - and if you need more specificity, then you can manually mark the type as I have done above. I think the existing behaviour is quite sensible so this issue should probaly be closed.

**Comment by mattpocock** [comment]
Closing, @JakeTrevor is correct.
