### ISSUE TITLE
Reset localStorage and sessionStorage

### ISSUE THREAD

**Issue by kentcdodds** [total-typescript/ts-reset#158]
Right now these are typed like so:

```ts
interface Storage {
    readonly length: number;
    clear(): void;
    getItem(key: string): string | null;
    removeItem(key: string): void;
    setItem(key: string, value: string): void;
    [name: string]: any;
}
```

So doing this is totally cool:

```ts
sessionStorage.blah()
localStorage.i.make.devs.cry()
```

But there's no world where that would be ok.

I'm not sure whether this is possible. Me and ChatGPT couldn't figure out how to augment the built-in Session interface successfully 🙃

**Comment by kentcdodds** [comment]
I made [a TypeScript playground](https://www.typescriptlang.org/play?target=9&module=7#code/KYDwDg9gTgLgBAbwL4G4BQaAmwDGAbAQymDgHM8IAjAvRNASAEsA7GYKAMwJxIGUZoBUiQQN6AbWYEAtsABccAM4woLUgF0FAV2YBrZhADuzBkjRm0AektwAAjEUBaUGFwxnUKNDgwAFo0UlXwgtPEw4ShJGaUhFRUZKPHk0ChwafkFhADpGLOkCXWAs7AA3RSycKABPAAoASgxrOF8YGDBFOWtSRj8tSgqIaUsBGBpHGCrXRUrGMBhhp2JFYHmAxS1gRUsARgBWAA40IA) for folks who want to try their hand at this...

**Comment by robbiespeed** [comment]
Hacky work around is to use template literals for the index signature, since overriding index signatures is not allowed.

For example this also doesn't work.
```
interface A {
  // TS Error: Duplicate index signature for type 'string'.(2374)
  [key: string]: any;
}
interface A {
  // TS Error: Duplicate index signature for type 'string'.(2374)
  [key: string]: unknown;
}
```
So I think the fact that it's an override of a global is just hiding the error, probably a TS bug.

This does work however:
```
type Character = 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z' | '_' | '$';

interface A {
  [key: string]: any;
}
interface A {
  [key: `${Character | Uppercase<Character>}${string}`]: unknown;
}
```

 [TS playground](https://www.typescriptlang.org/play?target=9&module=7#code/KYDwDg9gTgLgBAbwL4G4BQaYE8zDgYQAsBDKYgYxmCjgF44ByYhuAH0YCMX2HzvGAJvwbBhAM2EBzYYWEBLYQCthAa2EAbYQFthAO2ERhYYQEdhUYQGdhMYQFdhAN2EB3YSGFZhAL2EB9YQASBnQ0AWBydVI8SXUIDmJ1RDQASDldKigxCjwAZRhoYkk8BFSUgG1dYi1gAC44AANAhCJSCky2OABVMFwocmJLYAAeVrJKagA+JGbLGCh0ySQGgF16u10VXQgXXVSkNAO0AHpjuAABGEsAWlBcSluoKGg4GEI5SzhLQgg7dQE4Bw8HItJBLJY5Bx1HU0HEBup8oVigA6OTIrTEFTAZHhRyWZHkKBYAAUAEoMKc4IQYDAwJZaqdJHI3nYOASIFpjgUYIlrthcJZCXIwDAuTcoMAhqKPpY7JLjgBGACsAA40EA)

**Comment by mattpocock** [comment]
@robbiespeed This might actually be hacky enough to work. I just wish there was a way to cut down on that union type. Instantiating 52+ members is a bit expensive.

I'll ask the brain trust, see what comes back.

@kentcdodds I definitely agree that this is a great candidate for ts-reset, if possible.

**Comment by mattpocock** [comment]
Andarist is the GOAT:

https://twitter.com/AndaristRake/status/1689676010277457920

**Comment by mattpocock** [comment]
#160

**Comment by kentcdodds** [comment]
Fantastic! Thank you!

**Comment by kentcdodds** [comment]
What's the release process for this library?
